### PR TITLE
🐛(Search) fix filter pane quality issues on handheld devices

### PR DESCRIPTION
**Pull request by jbpenrath**
## Purpose

1. The button to open/close filter pane did not (dis)appear on window resize
2. There was quality issues on the search filter pane on handheld devices

## Proposal

- [x] useMatchMedia hook to show/hide button on window resize
- [x] fix filter pane quality issues

Capture d’écran 2021-04-15 à 16 22 24-squashed-squashed
Capture d’écran 2021-04-15 à 16 21 55-squashed-squashed

### CODE REVIEW

**Review by kernicPanel — APPROVED** [review]
I didn't see anything wrong, but I don't think I'm able to approve it :/

**Comment by jbpenrath** [comment]
> I didn't see anything wrong, but I don't think I'm able to approve it :/

Ok no problem, it is not a big issue. Let's see @mbenadda feedbacks.

**Review by mbenadda — CHANGES_REQUESTED** [review]
I think there's one more quality improvement to make, missing padding at the bottom of the sidebar

Capture d’écran 2021-04-16 à 10 30 34

Otherwise looks good to me.

**Review by mbenadda — APPROVED** [review]
GTM!

**Pull request merged**
