### PR TITLE
🔨(test) add script to run specific frontend test

### PR DESCRIPTION
**Pull request by igobranco**
Add `frontend-test` script that allows the developer to run a specific frontend test more easy.

### CODE REVIEW

**Comment by jbpenrath** [comment]
Hi Ivo :wave:

We could take the opportunity to also add a `test-front` command into the Makefile

What do you think ?

**Comment by igobranco** [comment]
@jbpenrath we already have a `test-front` Makefile target https://github.com/openfun/richie/blob/master/Makefile#L178-L180 what we don't have is an easy way to run a specific test.

**Comment by jbpenrath** [comment]
> @jbpenrath we already have a `test-front` Makefile target https://github.com/openfun/richie/blob/master/Makefile#L178-L180 what we don't have is an easy way to run a specific test.

My intent was to update test-front make command to accept extra args. I find it simpler for developer to have only one command. What do you think 

```
test-front: ## run front-end tests
	@args="$(filter-out $@,$(MAKECMDGOALS))" && \
	bin/frontent-test $${args:-${1}}
.PHONY: test-front
```

```
test-front: ## run front-end tests
	@args="$(filter-out $@,$(MAKECMDGOALS))" && \
	$(YARN) test $${args:-${1}}
.PHONY: test-front
```

**Comment by igobranco** [comment]
@jbpenrath  done.
I alo agree that we should use Makefile as the starting point for every command that a developer needs, because it is much simpler to run `make help` and view all the necessary commands for the project.
I've also included you code for the `test-back` Makefile target.

**Review by jbpenrath — APPROVED** [review]
Great 🚀 
In this way we are also able to run back tests from their name.
e.g: `make test-back -- -k test_models`

**Pull request merged**
