### PR TITLE
🔖(chore) bump release to version 2.13.0

### PR DESCRIPTION
**Pull request by sampaccoud**
### Added

- Wrap React widgets in a `ErrorBoundary`
- Add settings to setup Joanie
- Add course runs to the course search API
- Add autocomplete feature on Page select in page related plugins

### Changed

- Show organization acronym by using the `menu_title` field (if set) on the organization page.
- Improve pagination blocks labels for screen reader users when there are multiple pagination components on one page
- Use the new `createWebStoragePersistor` to persist React query state
- Upgrade mysql to version 8

### CODE REVIEW

**Review by jbpenrath — APPROVED** [review]
This is now a thing of the past 🎉 
LGTM

**Comment by igobranco** [comment]
Can we merge this https://github.com/openfun/richie/pull/1584 before ?

**Comment by igobranco** [comment]
@sampaccoud please add latest lines to the commit message...

```
- Differentiate between Google Analytics and Google Tag Manager js code as
  different Web Analytics providers.
- Send web analytics event when an user enrolls to a course using the
  LMS enrollment api.
```

**Comment by sampaccoud** [comment]
> @sampaccoud please add latest lines to the commit message...

Good catch! Done. :pray:

**Pull request merged**
