### PR TITLE
🐛(lti_consumer)  Add missing language parameter in LTI requests

### PR DESCRIPTION
**Pull request by sampaccoud**
## Purpose

The LTI consumer was not transmitting the language when making an LTI launch request. As a result, marsha was serving the english language on our french sites.

## Proposal

Add missing language parameter in LTI requests and set it with the current language.

### CODE REVIEW

**Review by kernicPanel — COMMENTED** [review]
Shouldn't we have a test with another language than the default one ?

**Review by jbpenrath — COMMENTED** [review]
Agree with @kernicPanel, maybe write a test to check that cache is language sensitive.

**Comment by sampaccoud** [comment]
> Shouldn't we have a test with another language than the default one ?

Good idea! I'll do it later. Gotta move.

**Review by jbpenrath — APPROVED** [review]
LGTM ✅

**Pull request merged**
