### PR TITLE
⬆️(mysql) upgrade mysql to version 8

### PR DESCRIPTION
**Pull request by igobranco**
Upgrade mysql from 5.6 to 8.0

### CODE REVIEW

**Comment by sampaccoud** [comment]
Should we still keep mysql 6 in the CI alongside 8 since edX people are still running old versions of mysql?

**Comment by igobranco** [comment]
> Should we still keep mysql 6 in the CI alongside 8 since OpenEdX people are still running old versions of mysql?

Yes, we can have both versions running on CI.

@sampaccoud  Yesterday I forgot to add this issue https://github.com/openfun/richie/issues/1594

**Comment by igobranco** [comment]
@sampaccoud  I've added the CI configuration for: `test-back-mysql-5` and `test-back-mysql-8`.

**Review by sampaccoud — APPROVED** [review]
Nice!

**Comment by igobranco** [comment]
@sampaccoud I think needs to be a repo administrator to click on the Rebase and merge button. 
I've renamed the `test-back-mysql` to `test-back-mysql-5` CI step, because of that the old `test-back-mysql` haven't run. So the Github don't allow me to click on the Rebase and merge button.

**Pull request merged**
