### PR TITLE
✨(persons) allow linking person plugins on a person's page

### PR DESCRIPTION
**Pull request by sampaccoud**
## Purpose

Some person pages are in fact collectives. In this case, we want to include thumbnails of the persons in this collective.

## Proposal

Allow the person plugin on the person detail page.

closes https://github.com/openfun/richie/issues/1239

### CODE REVIEW

**Review by jbpenrath — COMMENTED** [review]
I suggested you to update styles of `.person-detail__row` to accept a column to display properly person plugin or glimpse plugin. https://github.com/openfun/richie/pull/1254/commits/b9eb67a395fa7cc1fd199f47a88d0abd024c4928

Capture d’écran 2021-01-20 à 13 44 00

Capture d’écran 2021-01-20 à 13 43 33

Also, I wonder if a new variant of the preview plugin should be created to have the same layout as a block person?

**Comment by sampaccoud** [comment]
@jbpenrath the way to add person plugins is to group them under a section. Did you try that?

**Comment by sampaccoud** [comment]
@jbpenrath good idea to add a glimpse variant that looks like a person.

**Comment by jbpenrath** [comment]
> @jbpenrath the way to add person plugins is to group them under a section. Did you try that?

You are right, SectionPlugin is far better than my fix to address this topic.

**Review by jbpenrath — APPROVED** [review]
LGTM!

**Pull request merged**
