### PR TITLE
Replaced ImagePlugin by PicturePlugin in setting file.

### PR DESCRIPTION
**Pull request by 2018D**
## Purpose

CMS_PLACEHOLDER_CONF had ImagePlugin to indicate that we wanted user to upload an image. The name of the plugin for that is PicturePlugin. So i replaced all instance of ImagePlugin by PicturePlugin in the setting file.

## Proposal
I replaced all instance of ImagePlugin by PicturePlugin in the setting file.

### CODE REVIEW

**Comment by sampaccoud** [comment]
@2018D CircleCI is failing with two checks:

- lint-back-black: run "make lint-back" on your laptop and black will correct your code's formatting.
- lint-git: your commit message must be formatted as documented here: https://openfun.gitbooks.io/handbook/content/git.html

**Comment by jmaupetit** [comment]
@2018D we recommend to install black on your machine and configure it for your editor, see https://black.readthedocs.io/en/stable/editor_integration.html

**Comment by 2018D** [comment]
Je ne comprend pas pourquoi le lint-git ne passe pas. Est-ce le scope qu'il ne comprend pas ou autre chose comme un espace qui manque?

**Comment by sampaccoud** [comment]
@2018D Oui c'est parce que tu as mis ":bug:" au lieu du caractère emoji. Si tu le prends sur le site gitmoji il faut sélectionner l'image et faire bouton droit / copier (pas cliquer sur le caractère car cela le copie sous la forme :bug:).

**Comment by jmaupetit** [comment]
FYI I've re-run failed jobs in CircleCI UI; Yarn install failed because of a bad response from npm servers  :sweat:

**Comment by 2018D** [comment]
Do i sqash and merge myself?

**Comment by sampaccoud** [comment]
@2018D We use "rebase and merge" from the github interface. Yes you can do it.

**Pull request merged**
