### PR TITLE
Reorganize the project's file structure

### PR DESCRIPTION
**Pull request by mbenadda**
## Purpose

Like we did on openfun/marsha, we're adopting the practice of grouping all source code related files into `src/`, split between frontend & backend files.

This helps us keep the project root as clean and simple as possible and should make it easier for observers and new contributors to get around in the project.

Related files such as linter config, dependencies, etc. should live alongside their code in those src/{part} folder.

## Proposal

- [x] Move all frontend related files into `src/frontend` (from `src/richie-front` and `./`)
- [ ] Move all backend related files into `src/backend`

### CODE REVIEW

**Comment by mbenadda** [comment]
I'm up for a review on this one 💁‍♂️

**Comment by mbenadda** [comment]
Ok I think `Makefile` commands work now.

I read https://docs.docker.com/engine/reference/builder/#dockerignore-file but I'm not sure what `.dockerignore` is really for or if I should update it.

**Comment by jmaupetit** [comment]
The `.dockerignore` file lists all paths that should be ignored when copying context data to a Dockerimage. I'll check this while handling the next step.

**Comment by jmaupetit** [comment]
@sampaccoud ping me here when you've merged your current PRs.

**Comment by jmaupetit** [comment]
@mbenadda I thought I would pursue your work here, no?

**Pull request merged**
