### PR TITLE
🔍️(SEO) add course cover to og image meta

### PR DESCRIPTION
**Pull request by igobranco**
Added the course cover image using 1200x630 size for the open graph og:image meta

### CODE REVIEW

**Comment by sampaccoud** [comment]
@igobranco we are finalizing PR https://github.com/openfun/richie/pull/1390 which is refactoring OpenGraph tags. Can you check if the subject of your PR is covered or make a PR directly on the [add-schema-metadata-courses](https://github.com/openfun/richie/tree/add-schema-metadata-courses) branch to improve it?

**Comment by igobranco** [comment]
It's almost the same, almost. 
What you have on your branch want work in PROD, because you have a CDN.
The `og:image` requires an absolute URL of the image.

Another thing, why do you decide to use 300x170 image? 
I think the minimum recommended size are 200x200. https://developers.facebook.com/docs/sharing/webmasters/images/

Can we use the maximum permitted value of 1200 x 630 ?

**Comment by sampaccoud** [comment]
> It's almost the same, almost.
> What you have on your branch want work in PROD, because you have a CDN.
> The `og:image` requires an absolute URL of the image.

Ok let's change this!

> Another thing, why do you decide to use 300x170 image?
> I think the minimum recommended size are 200x200. https://developers.facebook.com/docs/sharing/webmasters/images/
> Can we use the maximum permitted value of 1200 x 630 ?

You're right it seems to be Facebook's recommandation :+1:

**Comment by igobranco** [comment]
@sampaccoud ok, so I'm going to send a new PR to fix those on the add-schema-metadata-courses branch.

**Comment by igobranco** [comment]
Create a new PR https://github.com/openfun/richie/pull/1406

**Pull request closed without merging**
