### PR TITLE
🌐(translations) improve base strings

### PR DESCRIPTION
**Pull request by sandroscosta**
## Purpose
Improve original string to aid with translation.

## Description
As I was doing translations over Crowdin, I found these 2 strings on `PurchaseButton` that were really hard to translate to portuguese, due their punctuation. I propose some changes to aid future translations, including the one I'm taking care of.

### CODE REVIEW

**Review by jbpenrath — APPROVED** [review]
LGTM ✅

**Comment by sandroscosta** [comment]
I will rebase it and update it.

**Comment by sandroscosta** [comment]
@jbpenrath can we rebase and merge?

**Comment by jbpenrath** [comment]
> @jbpenrath can we rebase and merge?

Hi @sandroscosta, yes sure you can rebase this PR then merge it

**Comment by sandroscosta** [comment]
@jbpenrath Ok. will do that to close this issue.

**Pull request merged**
