### PR TITLE
💥 Fixed error connect with elasticsearch

### PR DESCRIPTION
**Pull request by leduong**
## Purpose

Solve the problem when `make bootstrap` cannot connect to `elasticsearch`

## Proposal
- [x] 💥 Fixed error connect with elasticsearch

### CODE REVIEW

**Comment by sampaccoud** [comment]
@leduong Nice to see that richie works with Elasticsearch 7.5 :astonished: 
Could you paste the error you got with Elasticsearch 6.6 as it should be working as well?

**Comment by leduong** [comment]
# Origin
image

# After
image

**Comment by sampaccoud** [comment]
@leduong Sorry I was busy on something else. I think you are a victim of this configuration trick: https://github.com/openfun/richie/blob/master/docs/docker-development.md#elasticsearch-service-is-always-down

Can you try to follow the instructions in this section of the docs to see if it solves it with Elasticsearch 6.6?

**Comment by leduong** [comment]
Thanks of alot @sampaccoud

**Comment by sampaccoud** [comment]
> Thanks of alot @sampaccoud

So does it mean it works on your side with Elasticsearch 6.6 after this trick?

If yes, we should definitely upgrade to Elasticsearch 7 as it will avoid this bad experience for new comers. However, we will need to add an item in the CI to run tests for version 7 and still continue testing with Elasticsearch 6. 6 as well. Do you want to try to do this in your PR or should we close it and do the change on our side?

**Pull request closed without merging**
